# Generated by Django 4.0.4 on 2022-05-06 23:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='iöage',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
