# Generated by Django 4.0.4 on 2022-05-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_iöage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='iöage',
            new_name='image',
        ),
    ]
